 Numpy --> Numerical Python
 Advantage of Numpy Arrays
 1. Faster than Python Lists





In [1]:
import numpy as np

In [2]:
# List vs Numpy - Time Taken
from time import process_time

# Time taken by a list
python_list = [i for i in range(1000)]
start_time = process_time()

python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time-start_time)


0.0


In [3]:
# Let's do for the Numpy array 

np_array = np.array([i for i in range(10000)])

start_time = process_time()
np_array +=5
end_time = process_time()
print(f"Time taken by Numpy array: {end_time - start_time} seconds")




Time taken by Numpy array: 0.0 seconds


In [4]:
# Let's Deep dive into Numpy array
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [5]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# Creating the 1 dim array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1.shape)
# Creating a 2D array
arr2 = np.array([(1, 2, 3), (4, 5,6)])
print(arr2.shape)


(5,)
(2, 3)


In [9]:
# Now creating with mentioning the dtypes

arr3 = np.array([1, 2, 3, 4, 5], dtype=np.float64)
print(arr3)  # Output: [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


In [11]:
# Creating the array using the inital place holder's 

arr4 = np.zeros((2, 2))
print(f'Array with intially zero \n {arr4}')

arr5 = np.ones((2, 2))
print(f'Array with  initally one \n{arr5}')

arr6 = np.full((2, 2), 7)
print(f'Array with shape (2,2) and all the values are 7 ---> \n{arr6}')

arr7 = np.eye(2)
print(f'its an identity matrix \n {arr7}')



Array with intially zero 
 [[0. 0.]
 [0. 0.]]
Array with  initally one 
[[1. 1.]
 [1. 1.]]
Array with shape (2,2) and all the values are 7 ---> 
[[7 7]
 [7 7]]
its an identity matrix 
 [[1. 0.]
 [0. 1.]]


In [12]:
# Creating the values with random using the random function 

arr8 = np.random.random((2, 2))
print(f'Array with random values \n{arr8}')

arr9 = np.random.randint(1, 10, (2, 2))
print(f'Array with random integers \n{arr9}')


Array with random values 
[[0.12277874 0.5295895 ]
 [0.00295755 0.08210252]]
Array with random integers 
[[5 1]
 [7 5]]


In [14]:
# array for evenly spaced values 
x = np.linspace(0, 10, 6)
print(x)

[ 0.  2.  4.  6.  8. 10.]


In [15]:
# array for evenly spaced values --> specifying the step
y = np.arange(10,30,5)

print(y)

[10 15 20 25]


In [17]:
# Convert the list to a numpy array
list2 = [1,2,3,4,4,5]

np_array = np.asarray(list2)
print(np_array)

[1 2 3 4 4 5]


In [18]:
# Analysing the Numpy array

a = np.random.randint(10,90,(5,5))
print(a)

[[58 17 32 50 83]
 [75 29 11 11 35]
 [88 73 21 34 85]
 [39 61 64 23 12]
 [38 86 36 49 11]]


In [22]:
# array dim 
print(f'Shape of the array {a.shape}')
print(f'Dim of the array {a.ndim}')
print(f'num of element in the array {a.size}')
print(f'Checking the data type of the array {a.dtype}')

Shape of the array (5, 5)
Dim of the array 2
num of element in the array 25
Checking the data type of the array int32


In [25]:
# Mathmetical operation in the numpy array 

# 1. Addition

b = np.array([1,2,3,4,5])
c = np.array([6,7,8,9,10])

print(f'Addition of the two matrix --------   {b+c}')  # Output: [ 7  9 11 13 15 .....

# 2. Subtraction
print(f'subtraction of the two matrix-------- {b-c}')  # Output: [-5 -5 -5 -5 -5 .....

# 3. Multiplication
print(f'Multiplication of the two matrix ---- {b*c}')  # Output: [ 6 14 24 36 50 .....

# 4. Division
print(f'Division of the two matrix -----------{b/c}')  # Output: [0.16666667 0.28571429 0.375  0.44444444 0.5   .....

# 5. Exponentiation
print(f'Exponetion of the two matrix -------- {b**c}')  # Output: [   1    8   27


Addition of the two matrix --------   [ 7  9 11 13 15]
subtraction of the two matrix-------- [-5 -5 -5 -5 -5]
Multiplication of the two matrix ---- [ 6 14 24 36 50]
Division of the two matrix -----------[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Exponetion of the two matrix -------- [      1     128    6561  262144 9765625]


In [28]:
# Performing the Mathematical operation using the Inbuilt function of the numpy

print(f'Addition of the two matrix --------   {np.add(b,c)}')  # Output: [ 7  9 11 13 15 .....

print(f'Subtraction of the two matrix --------{np.subtract(b,c)}')  # Output: [-5 -5 -5 -5 -5 .....

print(f'Multiplication of the two matrix -----{np.multiply(b,c)}')  # Output: [ 6 14 24 36 50 .....

print(f'Division of the two matrix --------   {np.divide(b,c)}')  # Output: [0.16666667 0.28571429 0.375  0.44444444 0.5   .....

print(f'Exponentiation of the two matrix -----{np.power(b,c)}')  # Output: [   1    8   27 64  125 .....



Addition of the two matrix --------   [ 7  9 11 13 15]
Subtraction of the two matrix --------[-5 -5 -5 -5 -5]
Multiplication of the two matrix -----[ 6 14 24 36 50]
Division of the two matrix --------   [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Exponentiation of the two matrix -----[      1     128    6561  262144 9765625]


In [33]:
# Transpose of the martix
a = np.random.randint(10,90,(5,5))
print(f'Transpose of the matrix -----------> \n{a.T}')  # Output: [[ 1  4  7 10]


Transpose of the matrix -----------> 
[[12 55 71 73 44]
 [31 56 65 42 49]
 [46 17 81 37 89]
 [68 37 65 82 69]
 [13 86 12 41 14]]


In [36]:
# Reshaping the array 

a = np.random.randint(0,10,(5,3))
print("Original array: \n", a)

# Reshaping the array to 3x5
a = a.reshape(3,5)
print("Reshaped array: \n", a)

Original array: 
 [[6 9 8]
 [6 3 6]
 [7 1 3]
 [2 1 2]
 [4 1 9]]
Reshaped array: 
 [[6 9 8 6 3]
 [6 7 1 3 2]
 [1 2 4 1 9]]
