In [1]:
import numpy as np

In [2]:
# Let's Create the Matrix Do Operation on that Matrix

# Creating the Matrix 1
matrix_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Creating the Matrix 2
matrix_2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

In [6]:
# Lets Print the Both the Matrix
print('Matrix 1\n',matrix_1)
print('----------------------------')
print('Matrix 2\n',matrix_2)

Matrix 1
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------
Matrix 2
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


We need to perform the Matrix Operations 
Mentioned Below

1. Matrix Addition
2. Matrix Subtraction
3. Multiplying a Matrix by a Scalar
4. Multipying 2 Matrices

In [12]:
# Additon of the Two Matrices

addition_matrix = matrix_1 + matrix_2
print(addition_matrix)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [11]:
# Subtraction of the Two Matrices

subtraction_matrix = matrix_1 - matrix_2
print(subtraction_matrix)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [10]:
# Multiplying a Matrix by a Scalar

scalar = 2
multiplication_matrix = scalar * matrix_1
print(multiplication_matrix)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [13]:
# Multipying the Two Matrix

multiplication_result = np.dot(matrix_1, matrix_2)
print(multiplication_result)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
