In [1]:
import numpy as np

In [3]:
# Creating the Matrix using numpy

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
matrix.shape

(3, 3)

In [7]:
# Creating the Matrix with Different shape

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[11, 12, 13]])

print(matrix)

# Creating the Matrix with elements of different data types

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]]


In [8]:
matrix.shape

(4, 3)

In [9]:
# Create a matrix with random values

matrix = np.random.rand(3, 3)

print(matrix)

[[0.63537091 0.72650748 0.73229217]
 [0.65257577 0.62733991 0.31274871]
 [0.42079031 0.4916443  0.36014654]]


In [10]:
# Create a matrix with random integer

matrix = np.random.randint(1, 10, (3, 3))

print(matrix)

[[3 1 8]
 [3 1 6]
 [9 9 2]]


In [12]:
# Matrix with all the values with ones

matrix = np.ones((3, 3),dtype=int)

print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
# Null matrix or zero Matrix 

matrix = np.zeros((3, 3), dtype=int)

print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [14]:
# Identity Matrix

matrix = np.eye(3, dtype=int)

print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [20]:
# Transpose of the Matrix

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print('The matrix is \n' ,matrix,'shape of matrix is ',{matrix.shape})

print('The Transpose of  matrix is \n' ,matrix.T,'shape of matrix is ',{matrix.T.shape})



The matrix is 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] shape of matrix is  {(3, 3)}
The Transpose of  matrix is 
 [[1 4 7]
 [2 5 8]
 [3 6 9]] shape of matrix is  {(3, 3)}
